.PHONY: all dev format check clean build run rebuild dmg

all: clean build run
dev: rebuild run

format:
	find . -path ./build -prune -or \( \( -name "*.cpp" -or -name "*.h" \) -not -name "*Wx.cpp" -not -name "*Wx.h" \) -exec clang-format -i {} +

# Static analysis. Files generated by wxFormBuilder (*Wx.h / *Wx.cpp) are excluded.
# constParameterCallback is suppressed globally: wxWidgets' Bind() requires event
# handlers to take a non-const reference.
check:
	cppcheck --std=c++20 --enable=warning,style,performance,portability \
		--suppress=missingIncludeSystem \
		--suppress=constParameterCallback \
		--suppress="*:*Wx.h" --suppress="*:*Wx.cpp" \
		--inline-suppr --error-exitcode=1 -i build --quiet \
		libs apps

clean:
	rm -rf ./build ./dist

build:
	cmake -S . -B build -G Ninja && cmake --build build

run:
	open ./build/apps/rotreader/rotreader.app

rebuild:
	cmake --build build

# Build a distributable macOS disk image via CPack (DragNDrop).
# For a fully self-contained .dmg, configure with the vcpkg static path
# (cmake --preset ci-macos) so wx links statically instead of against Homebrew.
dmg: build
	cd build && cpack -G DragNDrop
