.PHONY: all dev format check clean build run rebuild

all: clean build run
dev: rebuild run

format:
	find . -path ./build -prune -or \( \( -name "*.cpp" -or -name "*.h" \) -not -name "*Wx.cpp" -not -name "*Wx.h" \) -exec clang-format -i {} +

# Static analysis. Files generated by wxFormBuilder (*Wx.h / *Wx.cpp) are excluded.
# constParameterCallback is suppressed globally: wxWidgets' Bind() requires event
# handlers to take a non-const reference.
check:
	cppcheck --std=c++20 --enable=warning,style,performance,portability \
		--suppress=missingIncludeSystem \
		--suppress=constParameterCallback \
		--suppress="*:*Wx.h" --suppress="*:*Wx.cpp" \
		--inline-suppr --error-exitcode=1 -i build --quiet \
		Backend Components HelperFunctions main.cpp

clean: 
	rm -rf ./build

build:
	cmake -B build && cmake --build build 

run:
	./build/mdreader

rebuild:
	cmake --build build
