cmake_minimum_required(VERSION 4.0)

add_subdirectory(MarkdownToHtmlAsync)
add_subdirectory(DirectoryScanner)

add_library(Backend INTERFACE)

target_include_directories(Backend INTERFACE MarkdownToHtmlAsync DirectoryScanner)
target_link_libraries(Backend INTERFACE MarkdownToHtmlAsync DirectoryScanner)
