# Reusable wxWidgets UI components.
add_subdirectory(FileDropTarget)
add_subdirectory(WebViewPanel)
add_subdirectory(HtmlSourcePanel)
add_subdirectory(FileBrowserTreePanel)
add_subdirectory(MarkdownPreviewPanel)
add_subdirectory(ScintillaTextEditorPanel)
add_subdirectory(MarkdownEditorPanel)
add_subdirectory(TextEditorPanel)
