# rottools_embed_window_icon(TARGET <t> PNGS <p>...)
#
# Compiles the given PNG files into <t> so it can set its window icon without
# reading anything from disk. Generates, in the target's binary dir:
#
#   generated/AppIconData.h    declares  kAppIconPngs / kAppIconPngCount
#   generated/AppIconData.cpp  defines them from the PNG bytes
#
# The app then does, once, in its frame constructor:
#
#   #include "AppIconData.h"
#   SetIcons(rottools::MakeIconBundle(kAppIconPngs, kAppIconPngCount));
#
# Reading the icon from a file instead would need a different path per install
# layout (.deb, portable .tar.gz, plain build tree), and would leave the build
# tree with no icon at all. See docs/graphics/README.md.
include_guard(GLOBAL)

# Formats a file's bytes as a C initialiser list, 16 bytes per line.
#
# The line breaks are not cosmetic: MSVC caps a source line at 16k characters,
# and one 256px PNG on a single line comes close to that. They are done with a
# SUBSTRING loop rather than a regex because CMake's regex flavour has no {n}
# repetition — "{16}" in a pattern would match those literal characters and the
# wrapping would silently do nothing.
function(_rottools_hex_bytes png out_var)
    file(READ "${png}" _hex HEX)
    string(LENGTH "${_hex}" _len)

    set(_bytes "")
    set(_pos 0)
    while(_pos LESS _len)
        math(EXPR _remaining "${_len} - ${_pos}")
        set(_take 32)  # 32 hex characters = 16 bytes
        if(_remaining LESS _take)
            set(_take ${_remaining})
        endif()
        string(SUBSTRING "${_hex}" ${_pos} ${_take} _line)
        string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _line "${_line}")
        string(APPEND _bytes "    ${_line}\n")
        math(EXPR _pos "${_pos} + 32")
    endwhile()

    set(${out_var} "${_bytes}" PARENT_SCOPE)
endfunction()

# Writes content to path only when it differs, so a re-configure does not touch
# the file's timestamp and force a needless recompile.
function(_rottools_write_if_different path content)
    set(_existing "")
    if(EXISTS "${path}")
        file(READ "${path}" _existing)
    endif()
    if(NOT "${_existing}" STREQUAL "${content}")
        file(WRITE "${path}" "${content}")
    endif()
endfunction()

function(rottools_embed_window_icon)
    set(oneValueArgs TARGET)
    set(multiValueArgs PNGS)
    cmake_parse_arguments(ICON "" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    if(NOT ICON_TARGET)
        message(FATAL_ERROR "rottools_embed_window_icon: TARGET is required")
    endif()
    if(NOT ICON_PNGS)
        message(FATAL_ERROR "rottools_embed_window_icon: PNGS is required")
    endif()

    set(_dir "${CMAKE_CURRENT_BINARY_DIR}/generated")
    file(MAKE_DIRECTORY "${_dir}")

    set(_arrays "")
    set(_table "")
    set(_index 0)
    foreach(_png IN LISTS ICON_PNGS)
        if(NOT EXISTS "${_png}")
            message(FATAL_ERROR "rottools_embed_window_icon: no such file: ${_png}")
        endif()
        # The bytes are read right here, at configure time, so a changed icon has
        # to trigger a re-configure.
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_png}")

        _rottools_hex_bytes("${_png}" _bytes)
        get_filename_component(_name "${_png}" NAME)
        string(APPEND _arrays "// ${_name}\nconst unsigned char kPng${_index}[] = {\n${_bytes}};\n\n")
        string(APPEND _table "    {kPng${_index}, sizeof(kPng${_index})},\n")
        math(EXPR _index "${_index} + 1")
    endforeach()

    _rottools_write_if_different("${_dir}/AppIconData.h"
"// Generated by rottools_embed_window_icon() — do not edit.
#pragma once

#include <cstddef>

#include \"AppIcon.h\"

extern const rottools::EmbeddedPng kAppIconPngs[];
extern const std::size_t kAppIconPngCount;
")

    _rottools_write_if_different("${_dir}/AppIconData.cpp"
"// Generated by rottools_embed_window_icon() — do not edit.
#include \"AppIconData.h\"

namespace {

${_arrays}}  // namespace

const rottools::EmbeddedPng kAppIconPngs[] = {
${_table}};
const std::size_t kAppIconPngCount = ${_index};
")

    target_sources(${ICON_TARGET} PRIVATE "${_dir}/AppIconData.cpp")
    target_include_directories(${ICON_TARGET} PRIVATE "${_dir}")
endfunction()
